### ISSUE TITLE
New Notice with WP 5.8

### ISSUE THREAD

**Issue by alexej-d** [junaidbhura/gumponents#27]
The following error is now appearing with your plugin, I think it ist related to your `wp_enqueue_script` setting `wp-editor` as a dep. The error appears on the new widget edit page, any ideas?
> Notice:  wp_enqueue_script() was called incorrectly. "wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets). […]

**Comment by junaidbhura** [comment]
Thanks for creating this issue @alexej-d . This has been resolved in `0.7.3`!
