### ISSUE TITLE
Any plans to release as an NPM package?

### ISSUE THREAD

**Issue by rleecrewmp** [junaidbhura/gumponents#35]
Sorry, I didn't know where to post this but I was wondering if you had any plans to release this as a package rather than a plugin. I love the components you offer but feel it would work better in my (and possibly others'?) workflow if I could pull it in as a dependency.

Working with clients, the risk is that somewhere down the line, they disable unrecognized plugins and break things.

**Comment by junaidbhura** [comment]
Hey @rleecrewmp

Thanks for creating this issue! Glad to see folks who use this plugin!

Since this is a WordPress plugin, you can install it via Composer, rather than NPM: https://www.smashingmagazine.com/2019/03/composer-wordpress/

There are no plans to release this via NPM
